### PR TITLE
grapho -> backfillz

### PR DESCRIPTION
**Pull request by rolyp**
Proposing minor correction to license

### CODE REVIEW

**Comment by rolyp** [comment]
ubuntu-20.04 build failed, but not an important enough change to worry about; closing.

**Review by jamestripp — COMMENTED** [review]
Excellent spot! Thanks, Rolyp

**Comment by jamestripp** [comment]
> ubuntu-20.04 build failed, but not an important enough change to worry about; closing.

Fixed. LazyData compression has been enabled. Thanks for pointing it out!

**Comment by rolyp** [comment]
No probs! I was a bit worried about wasting your time with something so minor, so I deleted the branch (but maybe you were able to accept the pull request anyway).

**Comment by jamestripp** [comment]
Please feel free to mention anything. I'll get to it when I can, and it makes the project better :)

I wasn't able to accept the pull request (maybe you had deleted it already) but I folded it into a new commit on my end.

Cheers,

James

**Pull request closed without merging**
